// Wails runtime bindings
// These types match the Go backend structures

export interface SDKInfo {
  name: string
  description: string
  homepage: string
  version: string
  installed: boolean
  versions: string[]
  current: string
}

export interface VersionInfo {
  version: string
  installed: boolean
  current: boolean
  description?: string
}

export interface OperationResult {
  success: boolean
  message: string
  error?: string
}

export interface PluginInfo {
  name: string
  version: string
  description: string
  homepage: string
  installed: boolean
}

export interface ConfigUpdate {
  proxy?: {
    url: string
    enable: boolean
  }
  storage?: {
    sdkPath: string
  }
  registry?: {
    address: string
  }
  cache?: {
    availableHookDuration: string
  }
  legacyVersionFile?: {
    enable: boolean
    strategy: string
  }
}

// Wails bindings - these are auto-generated by Wails
// @ts-ignore
declare global {
  interface Window {
    go: {
      main: {
        App: {
          GetInstalledSDKs: () => Promise<SDKInfo[]>
          GetAvailableVersions: (sdkName: string) => Promise<VersionInfo[]>
          InstallSDK: (sdkName: string, version: string) => Promise<OperationResult>
          UseSDK: (sdkName: string, version: string, scope: string) => Promise<OperationResult>
          UninstallSDK: (sdkName: string, version: string) => Promise<OperationResult>
          GetCurrentVersions: () => Promise<Record<string, string>>
          GetAvailablePlugins: () => Promise<PluginInfo[]>
          AddPlugin: (name: string, url: string) => Promise<OperationResult>
          RemovePlugin: (name: string) => Promise<OperationResult>
          SearchSDK: (sdkName: string, query: string) => Promise<VersionInfo[]>
          GetSDKInfo: (sdkName: string) => Promise<SDKInfo>
          CheckSDKExists: (sdkName: string, version: string) => Promise<boolean>
          GetConfig: () => Promise<Record<string, unknown>>
          SaveConfig: (update: ConfigUpdate) => Promise<OperationResult>
          Refresh: () => Promise<void>
          SelectDirectory: () => Promise<string>
        }
      }
    }
    runtime: {
      EventsEmit: (eventName: string, ...args: unknown[]) => void
      EventsOn: (eventName: string, callback: (...args: unknown[]) => void) => void
      EventsOff: (eventName: string) => void
      Quit: () => void
      LogDebug: (message: string) => void
      LogInfo: (message: string) => void
      LogWarning: (message: string) => void
      LogError: (message: string) => void
    }
  }
}

export {}
